version: '3'
services:
  db:
    image: mariadb:10.4.18
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "customer-tradie-projects"
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - quickbooks
#  phpmyadmin:
    #   image: phpmyadmin/phpmyadmin
    #restart: always
      #ports:
      #- '8080:80'
      #environment:
      #PMA_HOST: db
      #MYSQL_ROOT_PASSWORD: password
      #networks:
      #- quickbooks
  server:
    depends_on:
      - db
    restart: always

    environment:
      MYSQL_HOST: db
      MYSQL_DB: customer-tradie-projects
      MYSQL_PASSWORD: password
      MYSQL_USER: root
    build: ./API/
    networks:
      - quickbooks
    ports:
      - "8084:8084"
  app:
    depends_on:
      - server
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DB: customer-tradie-projects
      MYSQL_PASSWORD: password
      MYSQL_USER: root
    build: ./app/
    networks:
      - quickbooks
    ports:
      - "1234:80"

networks:
  quickbooks:
volumes:
  db_data: